import React, { useState, useEffect } from "react";
const STORES = {
  amazon:  { name:"Amazon",  emoji:"📦", color:"#FF9900", active:true,  tag:"lumanehair-21", buildUrl:(q,t)=>`https://www.amazon.com/s?k=${encodeURIComponent(q)}&tag=${t}` },
  sephora: { name:"Sephora", emoji:"🖤", color:"#E75480", active:true,  tag:"", buildUrl:(q)=>`https://www.sephora.com/search?keyword=${encodeURIComponent(q)}` },
  iherb:   { name:"iHerb",   emoji:"🌿", color:"#5AAA46", active:true,  tag:"TU_CODIGO_IHERB", buildUrl:(q,t)=>`https://www.iherb.com/search?kw=${encodeURIComponent(q)}&rcode=${t}` },
  druni:   { name:"Druni",   emoji:"💜", color:"#6B1F8A", active:true,  tag:"", buildUrl:(q)=>`https://www.druni.es/buscar?q=${encodeURIComponent(q)}` },
};
const HAIR_SYSTEM = [
  { id:"1A", group:"lacio",    emoji:"〰️", hue:38,  desc:"Lacio ultra fino. Tiende a ser graso." },
  { id:"1B", group:"lacio",    emoji:"〰️", hue:42,  desc:"Lacio normal con movimiento natural." },
  { id:"1C", group:"lacio",    emoji:"〰️", hue:46,  desc:"Lacio grueso con volumen. Frizz leve." },
  { id:"2A", group:"ondulado", emoji:"〜",  hue:180, desc:"Ondas suaves en S. Fácil de definir." },
  { id:"2B", group:"ondulado", emoji:"〜",  hue:185, desc:"Ondas medianas desde la raíz." },
  { id:"2C", group:"ondulado", emoji:"〜",  hue:190, desc:"Ondas pronunciadas casi rizos." },
  { id:"3A", group:"rizado",   emoji:"🌀", hue:280, desc:"Rizos amplios y brillantes." },
  { id:"3B", group:"rizado",   emoji:"🌀", hue:290, desc:"Rizos medianos y densos." },
  { id:"3C", group:"rizado",   emoji:"🌀", hue:300, desc:"Rizos apretados tipo lápiz." },
  { id:"4A", group:"afro",     emoji:"✦",  hue:30,  desc:"Coils suaves en S." },
  { id:"4B", group:"afro",     emoji:"✦",  hue:25,  desc:"Coils zigzag. Muy frágil." },
  { id:"4C", group:"afro",     emoji:"✦",  hue:20,  desc:"Coils ultra apretados." },
];

const PRICE_LABELS = {
  eco: { label:"💚 Eco",     color:"#5A9A5A", bg:"rgba(90,154,90,.1)",   border:"rgba(90,154,90,.3)" },
  mid: { label:"💛 Medio",   color:"#B8920A", bg:"rgba(184,146,10,.1)",  border:"rgba(184,146,10,.3)" },
  lux: { label:"💎 Premium", color:"#C4687A", bg:"rgba(196,104,122,.1)", border:"rgba(196,104,122,.3)" },
};
const FILTER_CATS = [
  { id:"all",       label:"Todos",        emoji:"✦",  sub:null },
  { id:"lacio",     label:"Lacio",        emoji:"〰️", sub:["1A","1B","1C"] },
  { id:"1A",        label:"1A",           emoji:"〰️", sub:null },
  { id:"1B",        label:"1B",           emoji:"〰️", sub:null },
  { id:"1C",        label:"1C",           emoji:"〰️", sub:null },
  { id:"ondulado",  label:"Ondulado",     emoji:"〜",  sub:["2A","2B","2C"] },
  { id:"2A",        label:"2A",           emoji:"〜",  sub:null },
  { id:"2B",        label:"2B",           emoji:"〜",  sub:null },
  { id:"2C",        label:"2C",           emoji:"〜",  sub:null },
  { id:"rizado",    label:"Rizado",       emoji:"🌀", sub:["3A","3B","3C"] },
  { id:"3A",        label:"3A",           emoji:"🌀", sub:null },
  { id:"3B",        label:"3B",           emoji:"🌀", sub:null },
  { id:"3C",        label:"3C",           emoji:"🌀", sub:null },
  { id:"afro",      label:"Afro/Coily",   emoji:"✦",  sub:["4A","4B","4C"] },
  { id:"4A",        label:"4A",           emoji:"✦",  sub:null },
  { id:"4B",        label:"4B",           emoji:"✦",  sub:null },
  { id:"4C",        label:"4C",           emoji:"✦",  sub:null },
  { id:"caspa",     label:"Caspa",        emoji:"❄️", sub:null },
  { id:"caida",     label:"Caída",        emoji:"🍂", sub:null },
  { id:"cuero",     label:"Cuero",        emoji:"🔬", sub:null },
  { id:"regenerar", label:"Regenerar",    emoji:"🌱", sub:null },
  { id:"hombre",    label:"Hombre",       emoji:"💪", sub:null },
  { id:"cal",       label:"Agua Cal",     emoji:"💧", sub:null },
];

const QUESTIONS = [
  { id:"gender",  icon:"🌍", q:"¿Con qué género te identificas?",
    opts:[{l:"Mujer",v:"mujer",i:"👩"},{l:"Hombre",v:"hombre",i:"👨"},{l:"No binario",v:"neutro",i:"🧑"}] },
  { id:"group",   icon:"〰️", q:"¿Cuál es el grupo general de tu cabello?",
    opts:[{l:"Lacio",v:"lacio",i:"〰️"},{l:"Ondulado",v:"ondulado",i:"〜"},{l:"Rizado",v:"rizado",i:"🌀"},{l:"Afro/Coily",v:"afro",i:"✦"}] },
  { id:"subtype", icon:"🔎", q:"¿Cuál describe mejor tu tipo específico?", opts:[] },
  { id:"scalp",   icon:"🔬", q:"¿Alguna preocupación con tu cuero cabelludo?",
    opts:[{l:"Caspa",v:"caspa",i:"❄️"},{l:"Cuero graso",v:"graso",i:"🍃"},{l:"Cuero sensible",v:"sensible",i:"🌸"},{l:"Todo bien",v:"normal",i:"✅"}] },
  { id:"concern", icon:"🎯", q:"¿Tu mayor preocupación capilar?",
    opts:[{l:"Caída excesiva",v:"caida",i:"🍂"},{l:"Frizz y volumen",v:"frizz",i:"⚡"},{l:"Cabello dañado",v:"dano",i:"💔"},{l:"Falta de brillo",v:"brillo",i:"✨"}] },
  { id:"damage",  icon:"🧪", q:"¿Tu cabello ha recibido tratamientos?",
    opts:[{l:"Tinte/decoloración",v:"tinte",i:"🎨"},{l:"Alisado/keratina",v:"quimico",i:"🧴"},{l:"Calor frecuente",v:"calor",i:"🔥"},{l:"Virgen y natural",v:"virgen",i:"🌱"}] },
];

const SUBTYPES = {
  lacio:   [{l:"1A — Ultrafino",v:"1A",i:"〰️"},{l:"1B — Liso normal",v:"1B",i:"〰️"},{l:"1C — Liso grueso",v:"1C",i:"〰️"}],
  ondulado:[{l:"2A — Ondas suaves",v:"2A",i:"〜"},{l:"2B — Ondas medianas",v:"2B",i:"〜"},{l:"2C — Ondas pronunciadas",v:"2C",i:"〜"}],
  rizado:  [{l:"3A — Rizos grandes",v:"3A",i:"🌀"},{l:"3B — Rizos medianos",v:"3B",i:"🌀"},{l:"3C — Rizos apretados",v:"3C",i:"🌀"}],
  afro:    [{l:"4A — Coils suaves",v:"4A",i:"✦"},{l:"4B — Coils zigzag",v:"4B",i:"✦"},{l:"4C — Ultra apretados",v:"4C",i:"✦"}],
};
const SHOP = [
  { id:1,  cat:"1A", step:"Limpieza",    emoji:"🫧", hue:38,  tag:"Esencial",  desc:"Limpieza sin peso que levanta la raíz del cabello fino.", sq:"volumizing shampoo fine straight hair", howTo:"1. Solo en cuero cabelludo.\n2. Masajea 2 min.\n3. Deja resbalar.\n4. Agua fría.\n5. Nunca en puntas.",
    prices:{eco:{price:6.99,name:"Shampoo Volumen Básico",brand:"Pantene"},mid:{price:14.99,name:"Shampoo Voluminizador 1A",brand:"OGX/Redken"},lux:{price:32.00,name:"Shampoo Volumen Pro",brand:"Kerastase"}} },
  { id:2,  cat:"1A", step:"Acondicionador",emoji:"💧",hue:40,  tag:"-20%",     desc:"Hidratación ultraligera que no aplana el cabello 1A.",     sq:"lightweight conditioner fine hair",        howTo:"1. Solo medios a puntas.\n2. Peina con dedos.\n3. 2 min.\n4. Agua fría.\n5. Nunca en raíz.",
    prices:{eco:{price:5.99,name:"Acondicionador Ligero",brand:"Dove"},mid:{price:13.99,name:"Acondicionador Sin Peso",brand:"OGX"},lux:{price:28.00,name:"Acondicionador Seda",brand:"Kerastase"}} },
  { id:3,  cat:"1B", step:"Limpieza",    emoji:"🫧", hue:42,  tag:"Bestseller",desc:"Equilibra el sebo y mantiene el brillo del lacio 1B.",      sq:"balancing shampoo straight normal hair",   howTo:"1. Cuero mojado.\n2. Circular 2 min.\n3. Espuma largos.\n4. Agua fría.\n5. 2-3x semana.",
    prices:{eco:{price:5.49,name:"Shampoo Liso Básico",brand:"Elvive"},mid:{price:12.99,name:"Shampoo Equilibrio Lacio",brand:"OGX"},lux:{price:29.00,name:"Shampoo Liso Perfecto",brand:"Kerastase"}} },
  { id:4,  cat:"1C", step:"Limpieza",    emoji:"🫧", hue:46,  tag:"Bestseller",desc:"Controla el volumen excesivo del liso grueso 1C.",           sq:"smoothing shampoo thick straight hair",    howTo:"1. Abundante cuero.\n2. Masajea 3 min.\n3. Trabaja espuma.\n4. Enjuaga bien.\n5. Siempre acondicionador.",
    prices:{eco:{price:5.99,name:"Shampoo Alisante Básico",brand:"Fructis"},mid:{price:13.99,name:"Shampoo Domador 1C",brand:"OGX"},lux:{price:31.00,name:"Shampoo Disciplina Pro",brand:"Kerastase"}} },
  { id:5,  cat:"2A", step:"Limpieza",    emoji:"🌊", hue:178, tag:"Esencial",  desc:"Limpia sin resecar las ondas suaves del tipo 2A.",           sq:"gentle shampoo wavy 2a sulfate free",      howTo:"1. Cuero cabelludo.\n2. No frotar largos.\n3. Deja resbalar.\n4. Agua fría.\n5. Solo 2x semana.",
    prices:{eco:{price:5.49,name:"Shampoo Suave 2A",brand:"Dove"},mid:{price:12.99,name:"Shampoo Ondas 2A",brand:"OGX"},lux:{price:28.00,name:"Shampoo Ondas Pro",brand:"DevaCurl"}} },
  { id:6,  cat:"2A", step:"Definición",  emoji:"〜", hue:180, tag:"Bestseller",desc:"Gel ultraligero que define las ondas 2A sin crunch.",         sq:"light defining gel wavy 2a",              howTo:"1. Muy húmedo secciones.\n2. Escrunching arriba.\n3. No tocar al secar.\n4. Disuelve crunch.\n5. Difusor media.",
    prices:{eco:{price:6.99,name:"Gel Definidor 2A",brand:"Eco Styler"},mid:{price:14.99,name:"Gel Ligero 2A",brand:"OGX"},lux:{price:30.00,name:"Gel Ondas Pro",brand:"DevaCurl"}} },
  { id:7,  cat:"2B", step:"Limpieza",    emoji:"🫧", hue:185, tag:"Bestseller",desc:"Sin sulfatos para mantener la hidratación de las ondas 2B.", sq:"co wash wavy 2b sulfate free",            howTo:"1. Generoso cuero.\n2. Masajea bien.\n3. Distribuye largos.\n4. 2 min.\n5. Enjuaga bien.",
    prices:{eco:{price:6.49,name:"Co-Wash 2B Básico",brand:"Cantu"},mid:{price:14.99,name:"Co-Wash Cremoso 2B",brand:"OGX"},lux:{price:29.00,name:"Co-Wash Nutritivo 2B",brand:"DevaCurl"}} },
  { id:8,  cat:"2B", step:"Definición",  emoji:"〜", hue:187, tag:"-23%",     desc:"Define ondas 2B sin rigidez. Hidrata y controla el frizz.",  sq:"curl cream defining wavy 2b",             howTo:"1. Húmedo tras acondicionador.\n2. Praying hands.\n3. Escruncha arriba.\n4. Difusor bajo.\n5. No tocar hasta seco.",
    prices:{eco:{price:7.49,name:"Crema Definidora 2B",brand:"Cantu"},mid:{price:15.99,name:"Crema Ondas 2B",brand:"Shea Moisture"},lux:{price:32.00,name:"Crema Pro 2B",brand:"DevaCurl"}} },
  { id:9,  cat:"2C", step:"Limpieza",    emoji:"🫧", hue:192, tag:"Bestseller",desc:"Método Curly Girl para ondas 2C. Sin sulfatos ni siliconas.", sq:"CGM shampoo wavy 2c curly girl",          howTo:"1. Cuero mojado.\n2. Masajea 3 min.\n3. Enjuaga tibia.\n4. Max 2-3 días.\n5. Siempre acondicionador.",
    prices:{eco:{price:6.49,name:"Shampoo CGM 2C",brand:"Cantu"},mid:{price:14.99,name:"Shampoo Curly Girl 2C",brand:"OGX"},lux:{price:30.00,name:"Shampoo CGM Pro",brand:"DevaCurl"}} },
  { id:10, cat:"3A", step:"Limpieza",    emoji:"🌀", hue:275, tag:"Bestseller",desc:"Sin sulfatos preservando la elasticidad de los rizos 3A.",   sq:"sulfate free shampoo curly 3a",           howTo:"1. Circular 2 min.\n2. No frotar largos.\n3. Enjuaga suave.\n4. Agua fría.\n5. 2-3x semana.",
    prices:{eco:{price:6.49,name:"Shampoo Rizos 3A",brand:"Cantu"},mid:{price:14.99,name:"Shampoo Suave 3A",brand:"OGX"},lux:{price:32.00,name:"Shampoo Rizos Pro",brand:"DevaCurl"}} },
  { id:11, cat:"3A", step:"Definición",  emoji:"🌀", hue:282, tag:"Nuevo",     desc:"Gel media fijación para rizos 3A con bounce y brillo.",      sq:"defining gel curly 3a bounce",            howTo:"1. Muy húmedo secciones.\n2. Praying hands.\n3. No separar.\n4. Difusor baja-media.\n5. Cast al 100% seco.",
    prices:{eco:{price:7.49,name:"Gel Rizos 3A",brand:"Eco Styler"},mid:{price:16.99,name:"Gel Definidor 3A",brand:"OGX"},lux:{price:34.00,name:"Gel Pro 3A",brand:"DevaCurl"}} },
  { id:12, cat:"3B", step:"Limpieza",    emoji:"🌀", hue:288, tag:"Bestseller",desc:"Limpieza con acondicionador para los aceites naturales 3B.",  sq:"co wash moisturizing curly 3b",           howTo:"1. Cuero y masajea.\n2. Distribuye rizos.\n3. 3 min.\n4. Enjuaga bien.\n5. Clarificante 1x mes.",
    prices:{eco:{price:6.49,name:"Co-Wash 3B",brand:"Cantu"},mid:{price:14.49,name:"Co-Wash Nutritivo 3B",brand:"Shea Moisture"},lux:{price:30.00,name:"Co-Wash Pro 3B",brand:"DevaCurl"}} },
  { id:13, cat:"3C", step:"Limpieza",    emoji:"🌀", hue:300, tag:"Bestseller",desc:"Sin sulfatos para rizos apretados 3C. Máxima hidratación.",  sq:"moisturizing shampoo tight curls 3c",      howTo:"1. Divide 4 secciones.\n2. Cuero cada sección.\n3. Masajea 3 min.\n4. Enjuaga.\n5. Nunca toalla, usa camiseta.",
    prices:{eco:{price:6.99,name:"Shampoo 3C",brand:"Cantu"},mid:{price:15.99,name:"Shampoo Hidratante 3C",brand:"Shea Moisture"},lux:{price:33.00,name:"Shampoo 3C Pro",brand:"DevaCurl"}} },
  { id:14, cat:"3C", step:"Hidratación", emoji:"💦", hue:303, tag:"-27%",     desc:"Acondicionador profundo que hidrata y define los rizos 3C.", sq:"deep conditioner tight curls 3c",         howTo:"1. Abundante tras shampoo.\n2. Peine ancho.\n3. Gorro + calor 30 min.\n4. Agua fría.\n5. Define inmediatamente.",
    prices:{eco:{price:7.49,name:"Deep Cond. 3C",brand:"Cantu"},mid:{price:16.99,name:"Deep Cond. Intenso 3C",brand:"Shea Moisture"},lux:{price:35.00,name:"Deep Cond. Luxe 3C",brand:"DevaCurl"}} },
  { id:15, cat:"4A", step:"Limpieza",    emoji:"✦",  hue:30,  tag:"Bestseller",desc:"Sin sulfatos que preserva la hidratación de los coils 4A.", sq:"sulfate free shampoo 4a coils",           howTo:"1. Divide 4 secciones.\n2. Cuero por sección.\n3. Masajea 3-4 min.\n4. Enjuaga tibia.\n5. Max 1-2x semana.",
    prices:{eco:{price:6.99,name:"Shampoo Coils 4A",brand:"Cantu"},mid:{price:15.49,name:"Shampoo Hidratante 4A",brand:"Shea Moisture"},lux:{price:32.00,name:"Shampoo 4A Pro",brand:"Camille Rose"}} },
  { id:16, cat:"4A", step:"Hidratación", emoji:"💧", hue:33,  tag:"-25%",     desc:"Hidratación intensiva para coils 4A. Método LOC recomendado.",sq:"deep conditioner 4a coils LOC",          howTo:"1. Húmedo sección a sección.\n2. Peine ancho.\n3. Gorro + calor 30-45 min.\n4. Agua fría.\n5. Leave-in inmediato.",
    prices:{eco:{price:7.99,name:"Acond. Profundo 4A",brand:"Cantu"},mid:{price:16.99,name:"Deep Cond. 4A",brand:"Shea Moisture"},lux:{price:34.00,name:"Deep Cond. Luxe 4A",brand:"Camille Rose"}} },
  { id:17, cat:"4B", step:"Limpieza",    emoji:"✦",  hue:25,  tag:"Bestseller",desc:"Co-wash ultra nutritivo para el patrón 4B en zigzag.",       sq:"co wash moisturizing 4b natural hair",     howTo:"1. Divide 8-10 secciones.\n2. Aplica y masajea.\n3. Solo presionar.\n4. Enjuaga sección.\n5. Alterna shampoo cada 2-3.",
    prices:{eco:{price:6.49,name:"Co-Wash 4B",brand:"Cantu"},mid:{price:14.99,name:"Co-Wash 4B Zigzag",brand:"Shea Moisture"},lux:{price:31.00,name:"Co-Wash 4B Pro",brand:"Camille Rose"}} },
  { id:18, cat:"4C", step:"Hidratación", emoji:"✦",  hue:20,  tag:"Bestseller",desc:"Hidratación máxima para el cabello 4C más frágil.",          sq:"deep moisture treatment 4c ultra dry",     howTo:"1. Divide 10-12 secciones.\n2. Aplica generoso húmedo.\n3. Gorro + calor 45 min.\n4. Agua fría.\n5. Leave-in inmediato.",
    prices:{eco:{price:8.49,name:"Tratamiento 4C",brand:"Cantu"},mid:{price:17.99,name:"Deep Moisture 4C",brand:"Shea Moisture"},lux:{price:38.00,name:"Tratamiento Luxe 4C",brand:"Camille Rose"}} },
  { id:19, cat:"caspa", step:"Shampoo",  emoji:"❄️", hue:210, tag:"Bestseller",desc:"Zinc y ketoconazol que eliminan la caspa desde la primera semana.",sq:"anti dandruff shampoo zinc ketoconazole",howTo:"1. Cuero mojado.\n2. Masajea 3-5 min.\n3. Deja 2 min.\n4. Enjuaga bien.\n5. 3x semana primeras 4 semanas.",
    prices:{eco:{price:5.49,name:"Anti-Caspa Básico",brand:"Head&Shoulders"},mid:{price:12.99,name:"Anti-Caspa Zinc",brand:"Nizoral"},lux:{price:28.00,name:"Anti-Caspa Pro",brand:"Ducray"}} },
  { id:20, cat:"caida", step:"Tónico",   emoji:"🍂", hue:90,  tag:"Bestseller",desc:"Cafeína y biotina que estimulan el folículo y reducen la caída.",sq:"hair loss tonic biotin caffeine",        howTo:"1. Zonas de caída.\n2. Circular 5 min.\n3. No enjuagar.\n4. Cada noche.\n5. Resultados 8-12 semanas.",
    prices:{eco:{price:7.99,name:"Tónico Anticaída",brand:"Alpecin"},mid:{price:16.99,name:"Tónico Biotina + Cafeína",brand:"Vichy"},lux:{price:35.00,name:"Tónico Anticaída Pro",brand:"Kerastase"}} },
  { id:21, cat:"cuero", step:"Exfoliante",emoji:"🔬",hue:160, tag:"Bestseller",desc:"Azúcar y ácido glicólico que eliminan células muertas.",       sq:"scalp scrub exfoliant glycolic acid",      howTo:"1. Cuero mojado antes shampoo.\n2. Circular 3-5 min.\n3. 2 min.\n4. Enjuaga y shampoo.\n5. 1x semana.",
    prices:{eco:{price:6.49,name:"Exfoliante Cuero",brand:"Garnier"},mid:{price:14.99,name:"Exfoliante Pro",brand:"Briogeo"},lux:{price:30.00,name:"Exfoliante Luxe",brand:"Christophe Robin"}} },
  { id:22, cat:"regenerar",step:"Mascarilla",emoji:"🌱",hue:120,tag:"Bestseller",desc:"Ricino, argán y mango que regeneran el cabello dañado.",    sq:"hair regenerating mask castor argan",      howTo:"1. Húmedo raíz a puntas.\n2. Divide secciones.\n3. Gorro + calor 25-30 min.\n4. Agua fría.\n5. 2x semana primeras 4 semanas.",
    prices:{eco:{price:6.99,name:"Mascarilla Reparadora",brand:"Garnier"},mid:{price:16.99,name:"Mascarilla Renacimiento",brand:"OGX"},lux:{price:38.00,name:"Mascarilla Pro",brand:"Olaplex"}} },
  { id:23, cat:"hombre", step:"Limpieza",emoji:"💪", hue:220, tag:"Bestseller",desc:"Shampoo + acondicionador para hombres activos. Frescura duradera.",sq:"2 in 1 shampoo conditioner men",       howTo:"1. Cabello mojado.\n2. Masajea 2-3 min.\n3. Distribuye largos.\n4. 1 min.\n5. Enjuaga bien.",
    prices:{eco:{price:5.49,name:"2-en-1 Hombre Básico",brand:"H&S Men"},mid:{price:12.99,name:"2-en-1 Active Fresh",brand:"American Crew"},lux:{price:28.00,name:"Shampoo Hombre Premium",brand:"Jack Black"}} },
  { id:24, cat:"hombre", step:"Anticaída",emoji:"⚡", hue:210, tag:"-20%",    desc:"Cafeína y zinc para frenar la caída masculina.",               sq:"hair loss tonic men caffeine zinc",        howTo:"1. Zonas de menor densidad.\n2. Circular 5 min.\n3. No enjuagar.\n4. Cada noche.\n5. Resultados 8-16 semanas.",
    prices:{eco:{price:8.99,name:"Tónico Anticaída Hombre",brand:"Alpecin"},mid:{price:18.99,name:"Tónico Men Forte",brand:"Vichy"},lux:{price:38.00,name:"Tónico Premium Hombre",brand:"Kerastase"}} },
  { id:25, cat:"cal", step:"Quelante",   emoji:"💧", hue:200, tag:"Esencial",  desc:"Elimina depósitos de cal del agua dura que apagan el brillo.", sq:"chelating shampoo hard water limescale",  howTo:"1. Generoso en mojado.\n2. Masajea 3-5 min.\n3. 2 min extra.\n4. Enjuaga bien.\n5. 1x semana.",
    prices:{eco:{price:7.99,name:"Shampoo Quelante Básico",brand:"Fructis"},mid:{price:16.99,name:"Shampoo Anti-Cal",brand:"Malibu C"},lux:{price:34.00,name:"Shampoo Quelante Pro",brand:"Olaplex"}} },
  { id:26, cat:"cal", step:"Filtro",     emoji:"🚿", hue:195, tag:"Bestseller",desc:"Filtra cloro y minerales del agua dura antes de tocar tu cabello.",sq:"shower filter hard water vitamin C",    howTo:"1. Instala sin herramientas.\n2. Cambia cartucho 3-6 meses.\n3. Diferencia desde el 1er lavado.\n4. Compatible todo cabezal.\n5. Reduce caída por cal hasta 60%.",
    prices:{eco:{price:14.99,name:"Filtro Ducha Básico",brand:"Aquasana"},mid:{price:29.99,name:"Filtro Vitamina C",brand:"AquaBliss"},lux:{price:59.99,name:"Filtro Ducha Pro",brand:"Jolie"}} },
  { id:27, cat:"cal", step:"Tratamiento",emoji:"⚗️", hue:205, tag:"-25%",    desc:"Vitamina C neutraliza minerales y restaura el brillo perdido.", sq:"vitamin C hair treatment hard water",      howTo:"1. Limpio húmedo.\n2. Masajea 3 min.\n3. Gorro 5-10 min.\n4. Agua fría.\n5. 1x semana intensivo.",
    prices:{eco:{price:8.99,name:"Vitamina C Cabello",brand:"Garnier"},mid:{price:17.99,name:"Tratamiento Anti-Cal",brand:"Malibu C"},lux:{price:38.00,name:"Tratamiento Pro",brand:"Olaplex"}} },
  { id:28, cat:"cal", step:"Mascarilla", emoji:"🍋", hue:55,  tag:"Bestseller",desc:"Vinagre de sidra y ácido málico disuelven depósitos de cal.",  sq:"apple cider vinegar hair mask hard water", howTo:"1. Limpio húmedo.\n2. Masajea bien.\n3. 10-15 min.\n4. Enjuaga bien.\n5. El olor desaparece. 1x semana.",
    prices:{eco:{price:5.99,name:"Mascarilla Vinagre",brand:"Garnier"},mid:{price:13.99,name:"Mascarilla ACV Anti-Cal",brand:"dpHUE"},lux:{price:28.00,name:"Mascarilla Ácido Málico",brand:"Briogeo"}} },
];
